spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-consumer-group
      auto-offset-reset: latest
      enable-auto-commit: false
      max-poll-records: 1000
      fetch-min-bytes: 1048576           # 1 MB
      fetch-max-wait: 500
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        max.poll.interval.ms: 300000
        session.timeout.ms: 45000
        max.request.size: 10485760
        buffer-memory: 134217728          # 128 MB buffer for batching large records
        compression-type: zstd
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      compression-type: zstd
      linger-ms: 5
      batch-size: 65536
      buffer-memory: 67108864
    listener:
      ack-mode: manual_immediate
      concurrency: 10
      poll-timeout: 3000
      missing-topics-fatal: false
      observation-enabled: false
    retry:
      topic:
        enabled: true
        attempts: 3
        delay: 2s
        multiplier: 2.0
        dlt-suffix: "-dlt"

logging:
  level:
    org.springframework.kafka: INFO
    com.example.kafka: INFO
